# -*- coding: utf-8 -*-
"""Time -series-disaggregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzpFdByE4BE0Z1z1I6V6GR19-SGIeDu5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### uploading files from github

THD_url ="https://github.com/LumumbaAssumani/Time-series-disaggregation-/raw/main/total_heat_demand.csv "
abc_url ="https://github.com/LumumbaAssumani/Time-series-disaggregation-/raw/main/student_buildings_abc.csv "
b_d_url ="https://github.com/LumumbaAssumani/Time-series-disaggregation-/raw/main/student_building_d_daily.csv "
b_e_url ="https://github.com/LumumbaAssumani/Time-series-disaggregation-/raw/main/student_building_e_monthly.csv "

def fix_timestamp(val):
    if str(val).replace('.', '').isdigit():
        # Excel serial number (midnight rows) → convert to proper datetime
        return pd.Timestamp('1899-12-30') + pd.to_timedelta(float(val), unit='D')
    else:
        # Normal date string → parse as DD/MM/YYYY HH:MM
        return pd.to_datetime(val, dayfirst=True)

# ── Load raw CSVs ──────────────────────────────────────────────
thd = pd.read_csv(THD_url)
abc = pd.read_csv(abc_url)
d   = pd.read_csv(b_d_url)
e   = pd.read_csv(b_e_url)

thd.head(5)

# ── Rename columns ─────────────────────────────────────────────
thd.columns = ['Timestamp', 'THD']
abc.columns = ['Timestamp', 'A', 'B', 'C']
d.columns   = ['Date', 'D_daily']
e.columns   = ['Month', 'E_monthly']

thd['Timestamp'] = thd['Timestamp'].apply(fix_timestamp)
abc['Timestamp'] = abc['Timestamp'].apply(fix_timestamp)
d['Date']        = pd.to_datetime(d['Date'], dayfirst=True)
e['Month']       = pd.to_datetime(e['Month'])

# ── Sort chronologically ───────────────────────────────────────
thd = thd.sort_values('Timestamp').reset_index(drop=True)
abc = abc.sort_values('Timestamp').reset_index(drop=True)
d   = d.sort_values('Date').reset_index(drop=True)
e   = e.sort_values('Month').reset_index(drop=True)
thd.head()

start = max(
    thd['Timestamp'].min(),
    abc['Timestamp'].min(),
    d['Date'].min(),
    e['Month'].min()       # latest start → 2022-02-01, this drives the window
)

end = min(
    thd['Timestamp'].max(),
    abc['Timestamp'].max(),
    d['Date'].max(),
    e['Month'].max()       # earliest end → 2026-01-30, this drives the window
)

print(f"Common window: {start} → {end}")
print(f"Common window: {start} → {end}")

# Clip each dataset to that window
thd = thd[(thd['Timestamp'] >= start) & (thd['Timestamp'] <= end)].reset_index(drop=True)
abc = abc[(abc['Timestamp'] >= start) & (abc['Timestamp'] <= end)].reset_index(drop=True)
d   = d[(d['Date'] >= start) & (d['Date'] <= end)].reset_index(drop=True)
e   = e[(e['Month'] >= start) & (e['Month'] <= end)].reset_index(drop=True)

print(f"THD rows after clip : {len(thd)}")
print(f"ABC rows after clip : {len(abc)}")
print(f"D rows after clip   : {len(d)}")
print(f"E rows after clip   : {len(e)}")

thd = thd.set_index('Timestamp')
abc = abc.set_index('Timestamp')
d = d.set_index('Date')
e = e.set_index('Month')
thd.head()

plt.figure(figsize=(12,8))
plt.plot(thd.index, thd['THD'])
plt.show()

plt.figure(figsize=(12,8))
plt.plot(abc.index, abc['A'])
plt.plot(abc.index, abc['B'])
plt.plot(abc.index, abc['C'])
plt.show()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(d.index, d['D_daily'])
ax2.plot(e.index, e['E_monthly'])
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(25, 10))
ax1, ax2, ax3, ax4 = axes.flatten()

ax1.plot(thd.index, thd['THD'])
ax1.set_ylabel('Demand MWh')
ax1.set_title('Total Heat Demand')

ax2.plot(abc.index, abc['A'])
ax2.set_ylabel('Demand MWh')
ax2.set_title('Student Building A')

ax3.plot(abc.index, abc['B'])
ax3.set_ylabel('Demand MWh')
ax3.set_title('Student Building B')

ax4.plot(abc.index, abc['C'])
ax4.set_ylabel('Demand MWh')
ax4.set_title('Student Building C')

plt.show()

d

"""### Removing errors from the plot"""

from os import remove

def remove_outliers (data , std):
  Q1 = np.percentile(data, 25)
  Q3 = np.percentile(data, 75)
  IQR = Q3 - Q1
  upper_threshold = Q3 + (std * IQR)
  cleaned = data.copy()
  cleaned[(data < 0) | (data > upper_threshold)] = np.nan
  return cleaned

A_clean = remove_outliers(abc['A'],1.5).copy()
B_clean = remove_outliers(abc['B'],1.5).copy()
C_clean = remove_outliers(abc['C'],1.5).copy()
D_clean = remove_outliers(d['D_daily'],1.5).copy()
E_clean = remove_outliers(e['E_monthly'],1.5).copy()

A_clean = A_clean.reindex(thd.index)
B_clean = B_clean.reindex(thd.index)
C_clean = C_clean.reindex(thd.index)

# Where THD = 0, set ABC to 0 (network is off, not missing data)
A_clean[thd['THD'] == 0] = 0
B_clean[thd['THD'] == 0] = 0
C_clean[thd['THD'] == 0] = 0

# Plot D as a time series of daily values
fig, ax = plt.subplots(figsize=(14, 4))
D_clean.plot(ax=ax, color='red', marker='o', markersize=2)
ax.set_xlabel('Date')
ax.set_ylabel('Heat Demand (normalised)')
ax.set_title('Building D — Daily Total Demand')
plt.tight_layout()
plt.show()

# Plot E as a time series of monthly values
fig, ax = plt.subplots(figsize=(14, 4))
E_clean.plot(ax=ax, color='purple', marker='o', markersize=4)
ax.set_xlabel('Date')
ax.set_ylabel('Heat Demand (normalised)')
ax.set_title('Building E — Monthly Total Demand')
plt.tight_layout()
plt.show()

thd.tail(5)

"""Plotting data that has been cleaned and the erros have been improved. what i could do is use the x values of the CHP and identify the gaps in data. From that i can look at imputation methods/load profiling?"""

import matplotlib.pyplot as plt

# 1. Resample the cleaned half-hourly data for A, B, and C to DAILY sums
A_daily = A_clean.resample('D').sum()
B_daily = B_clean.resample('D').sum()
C_daily = C_clean.resample('D').sum()

# 2. Plot the comparison
plt.figure(figsize=(14, 7))

# Plot the daily aggregated profiles for A, B, and C
plt.plot(A_daily.index, A_daily, label='Building A (Daily Sum)', alpha=0.7)
plt.plot(B_daily.index, B_daily, label='Building B (Daily Sum)', alpha=0.7)
plt.plot(C_daily.index, C_daily, label='Building C (Daily Sum)', alpha=0.7)

# Plot D_clean directly (since it is already in daily format)
# Using black and a thicker line to make it stand out against the others
plt.plot(D_clean.index, D_clean, label='Building D (Cleaned Daily)',
         color='black', linewidth=2.5)

# Formatting the chart
plt.title('Daily Heat Demand Comparison: Building D vs. Buildings A, B, C', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Heat Demand', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()

# Display the plot
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 1. Resample A, B, and C to DAILY sums (same as before)
A_daily = A_clean.resample('D').sum()
B_daily = B_clean.resample('D').sum()
C_daily = C_clean.resample('D').sum()

# 2. Combine them into one DataFrame to align the dates perfectly
# We use dropna() to ensure we are only comparing days where all meters were working
combined_daily = pd.DataFrame({
    'Building_A': A_daily,
    'Building_B': B_daily,
    'Building_C': C_daily,
    'Building_D': D_clean
}).dropna()

# 3. NORMALIZE: Scale all data between 0 and 1
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(combined_daily)
normalized_df = pd.DataFrame(normalized_data, columns=combined_daily.columns, index=combined_daily.index)

# 4. SMOOTH: Apply a 7-day rolling average to cut the noise
smoothed_df = normalized_df.rolling(window=7).mean()

# 5. Plot the Normalized & Smoothed comparison
plt.figure(figsize=(14, 7))

plt.plot(smoothed_df.index, smoothed_df['Building_A'], label='Building A', alpha=0.5, linestyle='--')
plt.plot(smoothed_df.index, smoothed_df['Building_B'], label='Building B', alpha=0.5, linestyle='--')
plt.plot(smoothed_df.index, smoothed_df['Building_C'], label='Building C', alpha=0.5, linestyle='--')

# Building D in bold black
plt.plot(smoothed_df.index, smoothed_df['Building_D'], label='Building D (Target)', color='black', linewidth=2.5)

# Formatting
plt.title('Normalized & Smoothed Daily Profiles (7-Day Rolling Average)', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Relative Demand (0 = Lowest, 1 = Highest)', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()

plt.show()

fig, axes = plt.subplots(4, 1, figsize=(25, 10))
ax1, ax2, ax3, ax4 = axes.flatten()

ax1.plot(thd.index, thd['THD'],c ='blue')
ax1.set_ylabel('Demand MWh')
ax1.set_title('Total Heat Demand' )

ax2.plot(A_clean.index,A_clean, c='purple')
ax2.set_ylabel('Demand MWh')
ax2.set_title('Student Building A')

ax3.plot(B_clean.index,B_clean, c= 'red')
ax3.set_ylabel('Demand MWh')
ax3.set_title('Student Building B')

ax4.plot(C_clean.index, C_clean, c= 'black')
ax4.set_ylabel('Demand MWh')
ax4.set_title('Student Building C')

plt.tight_layout()

plt.show()

fig, axes = plt.subplots(2, 2, figsize=(25, 10))
ax1, ax2, ax3, ax4 = axes.flatten()

ax1.plot(thd.index, thd['THD'], c='blue', lw=0.5)
ax1.set_ylabel('Demand MWh')
ax1.set_title('Total Heat Demand')

ax2.plot(thd.index, A_clean, c='purple', lw=0.5)
ax2.fill_between(thd.index, 0, A_clean.max(skipna=True),
                 where=A_clean.isna(),
                 color='red', alpha=0.3,
                 label=f'Missing: {A_clean.isna().sum() / len(thd) * 100:.1f}%')
ax2.set_ylabel('Demand MWh')
ax2.set_title('Student Building A')
ax2.legend(fontsize=9)

ax3.plot(thd.index, B_clean, c='red', lw=0.5)
ax3.fill_between(thd.index, 0, B_clean.max(skipna=True),
                 where=B_clean.isna(),
                 color='red', alpha=0.3,
                 label=f'Missing: {B_clean.isna().sum() / len(thd) * 100:.1f}%')
ax3.set_ylabel('Demand MWh')
ax3.set_title('Student Building B')
ax3.legend(fontsize=9)

ax4.plot(thd.index, C_clean, c='black', lw=0.5)
ax4.fill_between(thd.index, 0, C_clean.max(skipna=True),
                 where=C_clean.isna(),
                 color='red', alpha=0.3,
                 label=f'Missing: {C_clean.isna().sum() / len(thd) * 100:.1f}%')
ax4.set_ylabel('Demand MWh')
ax4.set_title('Student Building C')
ax4.legend(fontsize=9)

plt.tight_layout()
plt.show()

# Create a figure and a single subplot
fig, ax1 = plt.subplots(figsize=(8, 6))

# Plotting the time series
ax1.plot(A_clean, label='Series A', color='blue')
ax1.plot(B_clean, label='Series B', linestyle='--', color='orange')

# Setting the title and legend
ax1.set_title('Original Time Series')
ax1.legend()

plt.show()

A_profile = A_clean.groupby(A_clean.index.time).mean().values
B_profile = B_clean.groupby(B_clean.index.time).mean().values
C_profile = C_clean.groupby(C_clean.index.time).mean().values
THD_profile = thd.groupby(thd.index.time).mean().values

A_clean.index.time[:10]

!pip install dtaidistance

from dtaidistance import dtw

# Compare individual building profiles against each other
dist_AB = dtw.distance(A_profile, B_profile)
dist_AC = dtw.distance(A_profile, C_profile)
dist_BC = dtw.distance(B_profile, C_profile)

print(f"DTW distance A vs B: {dist_AB:.4f}")
print(f"DTW distance A vs C: {dist_AC:.4f}")
print(f"DTW distance B vs C: {dist_BC:.4f}")

from scipy.stats import zscore

# 2. Normalize the profiles using Z-score standardization
A_norm = zscore(A_profile)
B_norm = zscore(B_profile)
C_norm = zscore(C_profile)
THD_norm = zscore(THD_profile)

# 3. Calculate DTW distances on the NORMALIZED profiles
dist_AB_norm = dtw.distance(A_norm, B_norm)
dist_AC_norm = dtw.distance(A_norm, C_norm)
dist_BC_norm = dtw.distance(B_norm, C_norm)

### calculating the difference of the normalised profiles forTHD

dist_THD_A_norm = dtw.distance(A_norm, THD_norm)
dist_THD_B_norm = dtw.distance(B_norm, THD_norm)
dist_THD_C_norm = dtw.distance(C_norm, THD_norm)

print(f"Normalized DTW A vs B: {dist_AB_norm:.4f}")
print(f"Normalized DTW A vs C: {dist_AC_norm:.4f}")
print(f"Normalized DTW B vs C: {dist_BC_norm:.4f}")

print("---------------------------------------------")
print(f"Normalized DTW THD vs A: {dist_THD_A_norm:.4f}")
print(f"Normalized DTW THD vs B: {dist_THD_B_norm:.4f}")
print(f"Normalized DTW THD vs C: {dist_THD_C_norm:.4f}")

import matplotlib.pyplot as plt
import numpy as np

time_labels = [f"{h:02d}:{m:02d}" for h in range(24) for m in (0, 30)]

plt.figure(figsize=(12, 5))
plt.plot(A_profile, color='blue', label='Building A')
plt.plot(B_profile, color='orange', label='Building B')
plt.plot(C_profile, color='green', label='Building C')
plt.plot(THD_profile,color = 'purple',label ='CHP Plant')
plt.xticks(ticks=np.arange(48), labels=time_labels, rotation=90)
plt.xlabel('Time of Day')
plt.ylabel('Heat Demand MWh')
plt.title('Average Daily Load Profile — Building A')
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Generate the 30-minute time labels
time_labels = [f"{h:02d}:{m:02d}" for h in range(24) for m in (0, 30)]

# Create a figure with 2 subplots (2 rows, 1 column)
# Increased the height to 10 so both plots have enough room to breathe
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8 ))

# --- TOP PLOT: Buildings A, B, and C ---
ax1.plot(A_profile, color='blue', label='Building A')
ax1.plot(B_profile, color='orange', label='Building B')
ax1.plot(C_profile, color='green', label='Building C')

# Formatting for top plot
ax1.set_xticks(np.arange(48))
ax1.set_xticklabels(time_labels, rotation=90)
ax1.set_ylabel('Heat Demand MWh')
ax1.set_title('Average Daily Load Profiles — Buildings A, B, and C')
ax1.legend()
ax1.grid(True, alpha=0.3) # Added a light grid to make it easier to read values

# --- BOTTOM PLOT: THD (CHP Plant) ---
ax2.plot(THD_profile, color='purple', label='CHP Plant')

# Formatting for bottom plot
ax2.set_xticks(np.arange(48))
ax2.set_xticklabels(time_labels, rotation=90)
ax2.set_xlabel('Time of Day')
ax2.set_ylabel('Heat Demand MWh')
ax2.set_title('Average Daily Load Profile — CHP Plant (THD)')
ax2.legend()
ax2.grid(True, alpha=0.3)

# Automatically adjust spacing so the x-axis labels don't overlap with the bottom plot
plt.tight_layout()
plt.show()

distance, paths = dtw.warping_paths(B_profile, C_profile, use_c=False)
best_path = dtw.best_path(paths)
similarity_score = distance / len(best_path)

print(f"DTW distance A vs B: {distance:.4f}")
print(f"Normalised similarity score: {similarity_score:.4f}")

# Point-to-Point Comparison Plot
ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2)
ax3.plot(B_profile, label='Series B', color='blue', marker='o')
ax3.plot(C_profile, label='Series C', color='orange', marker='x', linestyle='--')
for a, b in best_path:
    ax3.plot([a, b], [B_profile[a], C_profile[b]], color='grey', linestyle='-', linewidth=1, alpha = 0.5)
ax3.set_title('Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

# Point-to-Point, normalised plot  B and C
ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2)
ax3.plot(B_norm, label='Series B norm', color='blue', marker='o')
ax3.plot(C_norm, label='Series C norm', color='orange', marker='x', linestyle='--')
for a, b in best_path:
    ax3.plot([a, b], [B_norm[a], C_norm[b]], color='grey', linestyle='-', linewidth=1, alpha = 0.5)
ax3.set_title('Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2)
ax3.plot(A_norm, label='Series A norm', color='blue', marker='o')
ax3.plot(C_norm, label='Series C norm', color='orange', marker='x', linestyle='--')
for a, b in best_path:
    ax3.plot([a, b], [A_norm[a], C_norm[b]], color='grey', linestyle='-', linewidth=1, alpha = 0.5)
ax3.set_title('Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2)
ax3.plot(A_norm, label='Series A norm', color='blue', marker='o')
ax3.plot(B_norm, label='Series B norm', color='orange', marker='x', linestyle='--')
for a, b in best_path:
    ax3.plot([a, b], [A_norm[a], B_norm[b]], color='grey', linestyle='-', linewidth=1, alpha = 0.5)
ax3.set_title('Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

# Point-to-Point Comparison Plot
ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2)
ax3.plot(A_profile, label='Series A', color='blue', marker='o')
ax3.plot(B_profile, label='Series B', color='orange', marker='x', linestyle='--')
for a, b in best_path:
    ax3.plot([a, b], [A_profile[a], B_profile[b]], color='grey', linestyle='-', linewidth=1, alpha = 0.5)
ax3.set_title('Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
# Assuming 'dtw' is already imported from dtaidistance

# 1. Calculate the specific paths
# Path for A vs B
_, paths_ab = dtw.warping_paths(A_norm, B_norm, use_c=False)
path_ab = dtw.best_path(paths_ab)

# Path for B vs C
_, paths_bc = dtw.warping_paths(B_norm, C_norm, use_c=False)
path_bc = dtw.best_path(paths_bc)

# Path for C vs A (Updated per your request)
_, paths_ca = dtw.warping_paths(C_norm, A_norm, use_c=False)
path_ca = dtw.best_path(paths_ca)


# 2. Create the Figure and Subplots
fig = plt.figure(figsize=(7, 6))

# --- SUBPLOT 1: A vs B ---
ax1 = plt.subplot2grid((3, 1), (0, 0))
ax1.plot(A_norm, label='Series A norm', color='blue', marker='o')
ax1.plot(B_norm, label='Series B norm', color='orange', marker='x', linestyle='--')
for a, b in path_ab:
    ax1.plot([a, b], [A_norm[a], B_norm[b]], color='grey', linestyle='-', linewidth=1, alpha=0.5)
ax1.set_title('A vs B: Point-to-Point Comparison After DTW Alignment')
ax1.legend()

# --- SUBPLOT 2: B vs C ---
ax2 = plt.subplot2grid((3, 1), (1, 0))
# Notice B stays Orange, C gets Green
ax2.plot(B_norm, label='Series B norm', color='orange', marker='o')
ax2.plot(C_norm, label='Series C norm', color='green', marker='x', linestyle='--')
for b, c in path_bc:
    ax2.plot([b, c], [B_norm[b], C_norm[c]], color='grey', linestyle='-', linewidth=1, alpha=0.5)
ax2.set_title('B vs C: Point-to-Point Comparison After DTW Alignment')
ax2.legend()

# --- SUBPLOT 3: C vs A ---
ax3 = plt.subplot2grid((3, 1), (2, 0))
# Notice C stays Green, A stays Blue
ax3.plot(C_norm, label='Series C norm', color='green', marker='o')
ax3.plot(A_norm, label='Series A norm', color='blue', marker='x', linestyle='--')
for c, a in path_ca:
    ax3.plot([c, a], [C_norm[c], A_norm[a]], color='grey', linestyle='-', linewidth=1, alpha=0.5)
ax3.set_title('C vs A: Point-to-Point Comparison After DTW Alignment')
ax3.legend()

plt.tight_layout()
plt.show()

len(A_profile)

# Create a monthly profile for each building
A_monthly = A_clean.groupby([A_clean.index.month, A_clean.index.time]).mean().unstack(level=0)
A_monthly = A_monthly.reset_index(drop=True)

B_monthly = B_clean.groupby([B_clean.index.month, B_clean.index.time]).mean().unstack(level=0)
B_monthly = B_monthly.reset_index(drop=True)

C_montly = C_clean.groupby([C_clean.index.month, C_clean.index.time]).mean().unstack(level=0)
C_montly = C_montly.reset_index(drop=True)

print(A_monthly.shape)  # should be 48 rows x 12 columns

import matplotlib.pyplot as plt
import numpy as np


fig , ax = plt.subplots(3,1,figsize=(14,12))
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

time_labels = [f"{h:02d}:{m:02d}" for h in range(24) for m in (0, 30)]


for i, month in enumerate(months):
    ax[0].plot(A_monthly.iloc[:, i], label=month)
    ax[1].plot(B_monthly.iloc[:, i], label=month)
    ax[2].plot(C_montly.iloc[:, i], label=month)

for axis, title in zip(ax, ['Building A', 'Building B', 'Building C']):
    axis.set_xticks(np.arange(48))
    axis.set_xticklabels(time_labels, rotation=90)
    axis.set_ylabel('Heat Demand (normalised)')
    axis.set_title(f'Monthly Load Profiles — {title}', fontsize = 12, fontweight ='bold')
    axis.legend(ncol=2)


plt.legend(ncol=2)
plt.tight_layout()
plt.show()

A_yearly = A_clean.groupby(A_clean.index.month).mean()
B_yearly = B_clean.groupby(B_clean.index.month).mean()
C_yearly = C_clean.groupby(C_clean.index.month).mean()

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

fig, ax = plt.subplots(3, 1, figsize=(14, 12))

ax[0].plot(A_yearly.values, marker='o', color='blue')
ax[1].plot(B_yearly.values, marker='o', color='orange')
ax[2].plot(C_yearly.values, marker='o', color='green')

for axis, title in zip(ax, ['Building A', 'Building B', 'Building C']):
    axis.set_xticks(np.arange(12))
    axis.set_xticklabels(months)
    axis.set_ylabel('Heat Demand (normalised)')
    axis.set_title(f'Monthly Average Demand — {title}')

plt.tight_layout(pad=3.0)
plt.show()

# Compute residual profile
residual_profile = THD_profile - (A_profile + B_profile + C_profile)

# Average profile for continuous type (B and C)
continuous_profile = (B_profile + C_profile) / 2

# Flatten all profiles to 1D arrays
residual_profile = residual_profile.flatten()
continuous_profile = continuous_profile.flatten()
A_profile_flat = A_profile.flatten()

# Now run DTW
dist_residual_continuous = dtw.distance(residual_profile, continuous_profile)
dist_residual_occupancy = dtw.distance(residual_profile, A_profile_flat)

print(f"Residual vs Continuous (B,C): {dist_residual_continuous:.4f}")
print(f"Residual vs Occupancy (A):    {dist_residual_occupancy:.4f}")

# Flatten THD_profile to 1D
THD_profile = THD_profile.flatten()

# Recompute residual
residual_profile = THD_profile - (A_profile.flatten() + B_profile.flatten() + C_profile.flatten())

# Verify shapes
print("THD_profile shape:", THD_profile.shape)        # should be (48,)
print("residual_profile shape:", residual_profile.shape)  # should be (48,)

time_labels = [f"{h:02d}:{m:02d}" for h in range(24) for m in (0, 30)]

plt.figure(figsize=(12, 5))
plt.plot(THD_profile, color='black', linestyle='--', label='Total CHP')
plt.plot(A_profile.flatten() + B_profile.flatten() + C_profile.flatten(), color='red', linestyle='--', label='A+B+C')
plt.plot(residual_profile, color='purple', label='Residual (D+E+F)')

plt.xticks(ticks=np.arange(48), labels=time_labels, rotation=90)
plt.xlabel('Time of Day')
plt.ylabel('Heat Demand (normalised)')
plt.title('Residual Profile vs Total CHP and A+B+C')
plt.legend()
plt.tight_layout()
plt.show()

"""#Gemini Code"""

import pandas as pd
import numpy as np

# 1. Start with your high-resolution indicator: the half-hourly THD
df_d_disagg = pd.DataFrame({'THD_HH': thd['THD']})

# 2. Create a 'Date' column (strips away the time, leaves just YYYY-MM-DD)
df_d_disagg['Date'] = df_d_disagg.index.normalize()

# 3. Calculate the total daily sum of the THD
daily_thd_sums = df_d_disagg.groupby('Date')['THD_HH'].sum()

# 4. Map those daily THD sums back to every half-hour row
df_d_disagg['THD_Daily_Sum'] = df_d_disagg['Date'].map(daily_thd_sums)

# 5. Map your cleaned daily Building D data to every half-hour row
# (This assigns D's daily total to all 48 half-hours in that specific day)
df_d_disagg['D_Daily_Target'] = df_d_disagg['Date'].map(D_clean)

# 6. THE MATH: Proportional Disaggregation
# Safely handle days where THD sum might be 0 to avoid dividing by zero errors
safe_divisor_d = df_d_disagg['THD_Daily_Sum'].replace(0, np.nan)

# Formula: (Half-Hour THD / Daily THD Sum) * Daily Target D
df_d_disagg['D_HH_Estimated'] = (df_d_disagg['THD_HH'] / safe_divisor_d) * df_d_disagg['D_Daily_Target']

# If the network was off (NaN from above), set the estimate to 0
df_d_disagg['D_HH_Estimated'] = df_d_disagg['D_HH_Estimated'].fillna(0)

# 7. Extract your final, high-resolution dataset for Building D!
D_half_hourly = df_d_disagg[['D_HH_Estimated']]

# Print the first few rows to see your new half-hourly data
print(D_half_hourly.head(50))

import matplotlib.pyplot as plt

# 1. Resample our newly created half-hourly data back to daily sums to verify
D_new_daily_check = D_half_hourly['D_HH_Estimated'].resample('D').sum()

# 2. Set up the plot
plt.figure(figsize=(14, 6))

# 3. Plot the Original Cleaned Daily Data
plt.plot(D_clean.index, D_clean, color='black', linewidth=3, alpha=0.5,
         label='Original Daily Meter (D_clean)')

# 4. Plot the New Disaggregated Data (resampled to daily) on top
plt.plot(D_new_daily_check.index, D_new_daily_check, color='red', linestyle='--', linewidth=2,
         label='New Disaggregated Data (Re-summed)')

# 5. Formatting the chart
plt.title('Building D: Daily Profile & Disaggregation Verification', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Heat Demand (Daily Total)', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()

# Display the plot
plt.show()